/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lapangan;

/**
 *
 * @author User
 */
public class mainpage extends javax.swing.JFrame {

    /**
     * Creates new form mainpage2
     */
    public mainpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        gambarfutsal = new javax.swing.JLabel();
        gambarbasket = new javax.swing.JLabel();
        gambarbadminton = new javax.swing.JLabel();
        buttonbadminton = new javax.swing.JButton();
        buttonbasket = new javax.swing.JButton();
        buttonfutsal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\futsal\\src\\main\\java\\com\\mycompany\\futsal\\logo.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gedung Olahraga Sidoarjo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 30));

        gambarfutsal.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\lapangan\\src\\main\\java\\com\\mycompany\\lapangan\\150x266.jpg")); // NOI18N
        getContentPane().add(gambarfutsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 120, 210, 120));

        gambarbasket.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\lapangan\\src\\main\\java\\com\\mycompany\\lapangan\\basket.jpg")); // NOI18N
        getContentPane().add(gambarbasket, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 280, 210, 120));

        gambarbadminton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\lapangan\\src\\main\\java\\com\\mycompany\\lapangan\\badminton2.jpg")); // NOI18N
        gambarbadminton.setText("badminton");
        getContentPane().add(gambarbadminton, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 430, 210, 140));

        buttonbadminton.setText("Badminton");
        buttonbadminton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonbadminton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbadmintonActionPerformed(evt);
            }
        });
        getContentPane().add(buttonbadminton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 166, 53));

        buttonbasket.setText("Basket");
        buttonbasket.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonbasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbasketActionPerformed(evt);
            }
        });
        getContentPane().add(buttonbasket, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 166, 53));

        buttonfutsal.setText("Futsal");
        buttonfutsal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonfutsal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                buttonfutsalComponentAdded(evt);
            }
        });
        buttonfutsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonfutsalActionPerformed(evt);
            }
        });
        getContentPane().add(buttonfutsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 166, 53));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\futsal\\src\\main\\java\\com\\mycompany\\futsal\\wallpaper-1600-29.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonbadmintonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbadmintonActionPerformed
        // TODO add your handling code here:
        int menu = 2;
        futsal main = new futsal(menu);
        main.setVisible(true);
    }//GEN-LAST:event_buttonbadmintonActionPerformed

    private void buttonbasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbasketActionPerformed
        // TODO add your handling code here:
        int menu = 3;
        futsal main = new futsal(menu);
        main.setVisible(true);
    }//GEN-LAST:event_buttonbasketActionPerformed

    private void buttonfutsalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_buttonfutsalComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonfutsalComponentAdded

    private void buttonfutsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonfutsalActionPerformed
        // TODO add your handling code here:
        int menu = 1;
        futsal main = new futsal(menu);
        main.setVisible(true);

    }//GEN-LAST:event_buttonfutsalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonbadminton;
    private javax.swing.JButton buttonbasket;
    private javax.swing.JButton buttonfutsal;
    private javax.swing.JLabel gambarbadminton;
    private javax.swing.JLabel gambarbasket;
    private javax.swing.JLabel gambarfutsal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
