/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lapangan;

/**
 *
 * @author User
 */
public class Struk extends javax.swing.JFrame {
    int pilihan;
    /**
     * Creates new form Struk
     */
    public Struk() {
        initComponents();
        
    }
    
    public Struk(String gedung, String lapang, String tanggal, String waktu, String nama, String hp) {
        initComponents();
        isigedung.setText(gedung);
        if(gedung == "Futsal"){
            pilihan = 1;
        }else if(gedung == "Badminton"){
            pilihan = 2;
        }else if(gedung == "Basket"){
            pilihan = 3;
        }
        isilapangan.setText(lapang);
        isitanggal.setText(tanggal);
        isiwaktu.setText(waktu);
        isinama.setText(nama);
        isihp.setText(hp);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labellapangan = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        labelwaktu = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        labelhp = new javax.swing.JLabel();
        labelgedung = new javax.swing.JLabel();
        isigedung = new javax.swing.JLabel();
        isilapangan = new javax.swing.JLabel();
        isitanggal = new javax.swing.JLabel();
        isiwaktu = new javax.swing.JLabel();
        isinama = new javax.swing.JLabel();
        isihp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelgedung1 = new javax.swing.JLabel();
        labellapangan1 = new javax.swing.JLabel();
        labeltanggal1 = new javax.swing.JLabel();
        labelwaktu1 = new javax.swing.JLabel();
        labelnama1 = new javax.swing.JLabel();
        labelhp1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        okbalikfutsal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gedung Olahraga Sidoarjo");

        labellapangan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labellapangan.setText("Lapangan");

        labeltanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeltanggal.setText("Tanggal Pemesanan");

        labelwaktu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelwaktu.setText("Waktu");

        labelnama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelnama.setText("Nama Pemesan");

        labelhp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelhp.setText("No Handphone");

        labelgedung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelgedung.setText("Gedung");

        isigedung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isigedung.setText("Gedung");

        isilapangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isilapangan.setText("Lapangan");

        isitanggal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isitanggal.setText("Tanggal Pemesanan");

        isiwaktu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isiwaktu.setText("Waktu");

        isinama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isinama.setText("Nama Pemesan");

        isihp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isihp.setText("No Handphone");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\futsal\\src\\main\\java\\com\\mycompany\\futsal\\logo.png")); // NOI18N

        labelgedung1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelgedung1.setText(":");

        labellapangan1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labellapangan1.setText(":");

        labeltanggal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeltanggal1.setText(":");

        labelwaktu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelwaktu1.setText(":");

        labelnama1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelnama1.setText(":");

        labelhp1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelhp1.setText(":");

        jLabel2.setText("*Diharapkan datang 10 menit sebelum jam booking");

        okbalikfutsal.setText("OK");
        okbalikfutsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbalikfutsalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeltanggal)
                            .addComponent(labelwaktu)
                            .addComponent(labelnama)
                            .addComponent(labelhp)
                            .addComponent(labellapangan)
                            .addComponent(labelgedung))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeltanggal1)
                            .addComponent(labelwaktu1)
                            .addComponent(labelnama1)
                            .addComponent(labelhp1)
                            .addComponent(labellapangan1)
                            .addComponent(labelgedung1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(isitanggal)
                            .addComponent(isiwaktu)
                            .addComponent(isinama)
                            .addComponent(isihp)
                            .addComponent(isilapangan)
                            .addComponent(isigedung)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okbalikfutsal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelgedung)
                        .addGap(19, 19, 19)
                        .addComponent(labellapangan)
                        .addGap(18, 18, 18)
                        .addComponent(labeltanggal)
                        .addGap(18, 18, 18)
                        .addComponent(labelwaktu)
                        .addGap(18, 18, 18)
                        .addComponent(labelnama)
                        .addGap(18, 18, 18)
                        .addComponent(labelhp))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelgedung1)
                                .addGap(19, 19, 19)
                                .addComponent(labellapangan1)
                                .addGap(18, 18, 18)
                                .addComponent(labeltanggal1)
                                .addGap(18, 18, 18)
                                .addComponent(labelwaktu1)
                                .addGap(18, 18, 18)
                                .addComponent(labelnama1)
                                .addGap(18, 18, 18)
                                .addComponent(labelhp1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isigedung)
                                .addGap(19, 19, 19)
                                .addComponent(isilapangan)
                                .addGap(18, 18, 18)
                                .addComponent(isitanggal)
                                .addGap(18, 18, 18)
                                .addComponent(isiwaktu)
                                .addGap(18, 18, 18)
                                .addComponent(isinama)
                                .addGap(18, 18, 18)
                                .addComponent(isihp)))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)))
                .addGap(36, 36, 36)
                .addComponent(okbalikfutsal)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okbalikfutsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbalikfutsalActionPerformed
        // TODO add your handling code here:
       
        futsal balik = new futsal(pilihan);
        balik.setVisible(true);
    }//GEN-LAST:event_okbalikfutsalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Struk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel isigedung;
    private javax.swing.JLabel isihp;
    private javax.swing.JLabel isilapangan;
    private javax.swing.JLabel isinama;
    private javax.swing.JLabel isitanggal;
    private javax.swing.JLabel isiwaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelgedung;
    private javax.swing.JLabel labelgedung1;
    private javax.swing.JLabel labelhp;
    private javax.swing.JLabel labelhp1;
    private javax.swing.JLabel labellapangan;
    private javax.swing.JLabel labellapangan1;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelnama1;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JLabel labeltanggal1;
    private javax.swing.JLabel labelwaktu;
    private javax.swing.JLabel labelwaktu1;
    private javax.swing.JButton okbalikfutsal;
    // End of variables declaration//GEN-END:variables
}
